source 'http://gems.ruby-china.com'

gem 'rough'
gem 'jekyll-paginate'
gem 'jekyll-geo-pattern'
gem 'kramdown'
gem 'jekyll-github-metadata'
gem 'jekyll-octicons'
gem 'nokogiri', '1.10.4'
gem 'actionview', '4.2.11.1'